name = "nautica1"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

[unsafe.metadata.observability]
enabled = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "0edca2f7-f90f-461e-bcdf-c8af52d26a35"
